# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
#- {name: 'Graphic Design',  folder: 'pages', file: 'graphic-design.html'}
#- {name: 'Motion Graphic Design',  folder: 'pages', file: 'motion-graphic-design.html'}
- {name: 'University Work', folder: 'pages', file: 'university-work.html'}
- {name: 'Bother Me',       folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter', link: 'https://twitter.com/'}
#- {icon: 'facebook', link: 'https://www.facebook.com/'}
- {icon: 'instagram', link: 'https://www.instagram.com/yvng_pei'}
- {icon: 'envelope', link: 'mailto:peiyu166@student.liu.se'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy...'

#post_date_prefix: 'Written on'
